INSERT INTO permisos (nombre, descripcion) VALUES
('mascota.create', 'Permite crear una mascota'),
('mascota.update', 'Permite actualizar una mascota'),
('mascota.disable', 'Permite deshabilitar una mascota'),
('mascota.view', 'Permite ver mascotas'),
('mascota.read', 'Permite leer información de mascotas'),
('mascota.*', 'Permite realizar todas las acciones sobre mascotas'),

('usuario.view', 'Permite ver usuarios'),
('usuario.read', 'Permite leer información de usuarios'),
('usuario.create', 'Permite crear un usuario'),
('usuario.update', 'Permite actualizar un usuario'),
('usuario.create-client', 'Permite crear clientes desde usuario'),
('usuario.create-personal', 'Permite crear personal desde usuario'),
('usuario.disable', 'Permite deshabilitar usuarios'),
('usuario.change-state', 'Permite deshabilitar usuarios'),
('usuario.*', 'Permite realizar todas las acciones sobre usuarios'),

('credencial.read', 'Permite leer credenciales'),
('credencial.create', 'Permite crear credenciales'),
('credencial.update', 'Permite actualizar credenciales'),
('credencial.*', 'Permite todas las acciones sobre credenciales'),

('rol-usuario.read', 'Permite leer asignaciones de roles a usuarios'),
('rol-usuario.create', 'Permite asignar roles a usuarios'),
('rol-usuario.update', 'Permite actualizar roles de usuarios'),
('rol-usuario.delete', 'Permite eliminar roles de usuarios'),
('rol-usuario.*', 'Permite todas las acciones sobre roles de usuarios'),

('rol.read', 'Permite leer roles'),
('rol.create', 'Permite crear roles'),
('rol.update', 'Permite actualizar roles'),
('rol.delete', 'Permite eliminar roles'),
('rol.*', 'Permite todas las acciones sobre roles'),

('permiso.read', 'Permite leer permisos'),
('permiso.create', 'Permite crear permisos'),
('permiso.update', 'Permite actualizar permisos'),
('permiso.delete', 'Permite eliminar permisos'),
('permiso.*', 'Permite todas las acciones sobre permisos'),

('permiso-rol.read', 'Permite leer permisos asignados a roles'),
('permiso-rol.create', 'Permite asignar permisos a roles'),
('permiso-rol.update', 'Permite actualizar permisos de roles'),
('permiso-rol.delete', 'Permite eliminar permisos de roles'),
('permiso-rol.*', 'Permite todas las acciones sobre permisos-roles'),

('tratamiento.view', 'Permite ver tratamientos'),
('tratamiento.read', 'Permite leer información de tratamientos'),
('tratamiento.create', 'Permite crear tratamientos'),
('tratamiento.update', 'Permite actualizar tratamientos'),
('tratamiento.delete', 'Permite eliminar tratamientos'),
('tratamiento.*', 'Permite todas las acciones sobre tratamientos'),

('venta.view', 'Permite ver ventas'),
('venta.read', 'Permite leer información de ventas'),
('venta.update', 'Permite actualizar ventas'),
('venta.create', 'Permite crear ventas'),
('venta.delete', 'Permite eliminar ventas'),
('venta.*', 'Permite todas las acciones sobre ventas'),

('medicamento-venta.read', 'Permite leer medicamentos de ventas'),
('medicamento-venta.create', 'Permite registrar medicamentos en ventas'),
('medicamento-venta.update', 'Permite actualizar medicamentos en ventas'),
('medicamento-venta.delete', 'Permite eliminar medicamentos de ventas'),
('medicamento-venta.*', 'Permite todas las acciones sobre medicamentos de ventas'),

('producto-venta.read', 'Permite leer productos de ventas'),
('producto-venta.create', 'Permite registrar productos en ventas'),
('producto-venta.update', 'Permite actualizar productos en ventas'),
('producto-venta.delete', 'Permite eliminar productos de ventas'),
('producto-venta.*', 'Permite todas las acciones sobre productos de ventas'),

('servicio-venta.read', 'Permite leer servicios de ventas'),
('servicio-venta.create', 'Permite registrar servicios en ventas'),
('servicio-venta.update', 'Permite actualizar servicios en ventas'),
('servicio-venta.delete', 'Permite eliminar servicios de ventas'),
('servicio-venta.*', 'Permite todas las acciones sobre servicios de ventas'),

('medicamento.view', 'Permite ver medicamentos'),
('medicamento.read', 'Permite leer información de medicamentos'),
('medicamento.create', 'Permite crear medicamentos'),
('medicamento.update', 'Permite actualizar medicamentos'),
('medicamento.delete', 'Permite eliminar medicamentos'),
('medicamento.*', 'Permite todas las acciones sobre medicamentos'),

('antecedente.view', 'Permite ver antecedentes'),
('antecedente.read', 'Permite leer información de antecedentes'),
('antecedente.create', 'Permite crear antecedentes'),
('antecedente.update', 'Permite actualizar antecedentes'),
('antecedente.delete', 'Permite eliminar antecedentes'),
('antecedente.*', 'Permite todas las acciones sobre antecedentes'),

('medicamento-tratamiento.view', 'Permite ver medicamentos de tratamientos'),
('medicamento-tratamiento.read', 'Permite leer medicamentos de tratamientos'),
('medicamento-tratamiento.create', 'Permite registrar medicamentos en tratamientos'),
('medicamento-tratamiento.update', 'Permite actualizar medicamentos de tratamientos'),
('medicamento-tratamiento.delete', 'Permite eliminar medicamentos de tratamientos'),
('medicamento-tratamiento.*', 'Permite todas las acciones sobre medicamentos de tratamientos'),

('info-medicamento.view', 'Permite ver información de medicamentos'),
('info-medicamento.read', 'Permite leer información de medicamentos'),
('info-medicamento.create', 'Permite registrar información de medicamentos'),
('info-medicamento.update', 'Permite actualizar información de medicamentos'),
('info-medicamento.delete', 'Permite eliminar información de medicamentos'),
('info-medicamento.*', 'Permite todas las acciones sobre información de medicamentos'),

('producto.view', 'Permite ver productos'),
('producto.read', 'Permite leer información de productos'),
('producto.create', 'Permite crear productos'),
('producto.update', 'Permite actualizar productos'),
('producto.delete', 'Permite eliminar productos'),
('producto.*', 'Permite todas las acciones sobre productos'),

('servicio.view', 'Permite ver servicios'),
('servicio.read', 'Permite leer información de servicios'),
('servicio.create', 'Permite crear servicios'),
('servicio.update', 'Permite actualizar servicios'),
('servicio.delete', 'Permite eliminar servicios'),
('servicio.*', 'Permite todas las acciones sobre servicios'),

('raza.view', 'Permite ver razas'),
('raza.read', 'Permite leer información de razas'),
('raza.create', 'Permite crear razas'),
('raza.update', 'Permite actualizar razas'),
('raza.delete', 'Permite eliminar razas'),
('raza.*', 'Permite todas las acciones sobre razas'),

('especie.view', 'Permite ver especies'),
('especie.read', 'Permite leer información de especies'),
('especie.create', 'Permite crear especies'),
('especie.update', 'Permite actualizar especies'),
('especie.delete', 'Permite eliminar especies'),
('especie.*', 'Permite todas las acciones sobre especies'),

('tipo-documento.read', 'Permite leer tipos de documento'),
('tipo-documento.create', 'Permite crear tipos de documento'),
('tipo-documento.update', 'Permite actualizar tipos de documento'),
('tipo-documento.delete', 'Permite eliminar tipos de documento'),
('tipo-documento.*', 'Permite todas las acciones sobre tipos de documento'),

('tipo-producto.view', 'Permite ver tipos de producto'),
('tipo-producto.create', 'Permite crear tipos de producto'),
('tipo-producto.update', 'Permite actualizar tipos de producto'),
('tipo-producto.delete', 'Permite eliminar tipos de producto'),
('tipo-producto.*', 'Permite todas las acciones sobre tipos de producto'),

('usuario.update-client', 'Permite crear clientes desde usuario'),
('usuario.view-client', 'Permite crear clientes desde usuario'),
('tipo-producto.read', 'Permite crear tipos de producto');

INSERT INTO permisos_roles (permiso_id, rol_id) VALUES
  (6, 1),
  (7, 1),
  (8, 1),
  (9, 1),
  (11, 1),
  (12, 1),
  (13, 1),
  (14, 1),
  (16, 1),
  (17, 1),
  (18, 1),
  (24, 1),
  (29, 1),
  (34, 1),
  (39, 1),
  (45, 1),
  (51, 1),
  (56, 1),
  (61, 1),
  (66, 1),
  (72, 1),
  (78, 1),
  (84, 1),
  (90, 1),
  (96, 1),
  (102, 1),
  (108, 1),
  (114, 1),
  (119, 1),
  (124, 1),
  (125, 1),
  (126, 1),
  (5, 1),
  (20, 1),
  (25, 1),
  (30, 1),
  (35, 1),
  (41, 1),
  (47, 1),
  (52, 1),
  (57, 1),
  (62, 1),
  (68, 1),
  (74, 1),
  (80, 1),
  (86, 1),
  (92, 1),
  (98, 1),
  (104, 1),
  (110, 1),
  (115, 1),
  (127, 1),
  (6, 2),
  (126, 2),
  (11, 2),
  (125, 2),
  (40, 2),
  (41, 2),
  (42, 2),
  (43, 2),
  (46, 2),
  (47, 2),
  (48, 2),
  (49, 2),
  (52, 2),
  (53, 2),
  (57, 2),
  (58, 2),
  (62, 2),
  (63, 2),
  (67, 2),
  (68, 2),
  (73, 2),
  (74, 2),
  (75, 2),
  (76, 2),
  (79, 2),
  (80, 2),
  (81, 2),
  (82, 2),
  (85, 2),
  (86, 2),
  (87, 2),
  (88, 2),
  (91, 2),
  (92, 2),
  (97, 2),
  (98, 2),
  (104, 2),
  (110, 2),
  (115, 2),
  (127, 2),
  (5, 2),
  (8, 2),
  (20, 2),
  (25, 2),
  (41, 2),
  (47, 2),
  (52, 2),
  (57, 2),
  (62, 2),
  (68, 2),
  (74, 2),
  (80, 2),
  (86, 2),
  (92, 2),
  (98, 2),
  (104, 2),
  (110, 2),
  (115, 2),
  (127, 2);
